components:
  schemas:
    AddFeedInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AddFeedInputBody.json
          format: uri
          readOnly: true
          type: string
        name:
          examples:
            - SKAI News
          maxLength: 80
          type: string
        url:
          examples:
            - https://www.skai.gr/feed.xml
          type: string
      required:
        - url
      type: object
    AddFeedOutputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/AddFeedOutputBody.json
          format: uri
          readOnly: true
          type: string
        feed:
          $ref: "#/components/schemas/Feed"
      required:
        - feed
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type:
            - array
            - "null"
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          examples:
            - https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          examples:
            - 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
            - Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          examples:
            - https://example.com/errors/example
          format: uri
          type: string
      type: object
    Feed:
      additionalProperties: false
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        url:
          type: string
      required:
        - id
        - url
        - name
      type: object
    FeedContent:
      additionalProperties: false
      properties:
        content:
          type: string
        description:
          type: string
        feed_id:
          format: int32
          type: integer
        id:
          format: int32
          type: integer
        is_read:
          type: boolean
        link:
          type: string
        title:
          type: string
      required:
        - id
        - title
        - description
        - link
        - content
        - is_read
        - feed_id
      type: object
    GetFeedItemOutputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/GetFeedItemOutputBody.json
          format: uri
          readOnly: true
          type: string
        item:
          $ref: "#/components/schemas/GetFeedItemRow"
      required:
        - item
      type: object
    GetFeedItemRow:
      additionalProperties: false
      properties:
        content:
          type: string
        description:
          type: string
        id:
          format: int32
          type: integer
        is_read:
          type: boolean
        link:
          type: string
        title:
          type: string
      required:
        - id
        - title
        - description
        - link
        - content
        - is_read
      type: object
    GetFeedItemsOutputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/GetFeedItemsOutputBody.json
          format: uri
          readOnly: true
          type: string
        items:
          items:
            $ref: "#/components/schemas/GetFeedItemsRow"
          type:
            - array
            - "null"
      required:
        - items
      type: object
    GetFeedItemsRow:
      additionalProperties: false
      properties:
        content:
          type: string
        description:
          type: string
        id:
          format: int32
          type: integer
        is_read:
          type: boolean
        link:
          type: string
        title:
          type: string
      required:
        - id
        - title
        - description
        - link
        - content
        - is_read
      type: object
    GetFeedsOutputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/GetFeedsOutputBody.json
          format: uri
          readOnly: true
          type: string
        feeds:
          items:
            $ref: "#/components/schemas/GetFeedsRow"
          type:
            - array
            - "null"
      required:
        - feeds
      type: object
    GetFeedsRow:
      additionalProperties: false
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        unread_items_count:
          format: int64
          type: integer
        url:
          type: string
      required:
        - id
        - url
        - name
        - unread_items_count
      type: object
    UpdateFeedItemInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/UpdateFeedItemInputBody.json
          format: uri
          readOnly: true
          type: string
        is_read:
          type: boolean
      required:
        - is_read
      type: object
    UpdateFeedItemOutputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/UpdateFeedItemOutputBody.json
          format: uri
          readOnly: true
          type: string
        item:
          $ref: "#/components/schemas/FeedContent"
      required:
        - item
      type: object
info:
  title: My API
  version: 1.0.0
openapi: 3.1.0
paths:
  /feeds:
    get:
      operationId: get-feeds
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetFeedsOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get all feeds
      tags:
        - Feeds
    post:
      operationId: post-feed
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddFeedInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddFeedOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Create a feed
      tags:
        - Feeds
  /feeds/{feedID}/items:
    get:
      operationId: get-feed-items
      parameters:
        - in: path
          name: feedID
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetFeedItemsOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get feed items
      tags:
        - Feeds, Item
  /feeds/{feedID}/items/{itemID}:
    get:
      operationId: get-feed-item
      parameters:
        - in: path
          name: itemID
          required: true
          schema:
            format: int32
            type: integer
        - in: path
          name: feedID
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetFeedItemOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get feed item
      tags:
        - Feeds, Item
    post:
      operationId: update-feed-item
      parameters:
        - in: path
          name: feedID
          required: true
          schema:
            format: int32
            type: integer
        - in: path
          name: itemID
          required: true
          schema:
            format: int32
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateFeedItemInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateFeedItemOutputBody"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Update feed item
      tags:
        - Feeds, Item
