services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_NAME: testdb
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes: 
    pgdata: 
    rabbitmq_data: