// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CountUnreadByFeedData,
  CountUnreadByFeedErrors,
  CountUnreadByFeedResponses,
  CountUnreadData,
  CountUnreadErrors,
  CountUnreadResponses,
  CreateFeedData,
  CreateFeedErrors,
  CreateFeedResponses,
  DeleteFeedData,
  DeleteFeedErrors,
  DeleteFeedResponses,
  GetFeedData,
  GetFeedErrors,
  GetFeedResponses,
  GetPostData,
  GetPostErrors,
  GetPostResponses,
  ListFeedsData,
  ListFeedsErrors,
  ListFeedsResponses,
  ListPostsData,
  ListPostsErrors,
  ListPostsResponses,
  MarkAllReadData,
  MarkAllReadErrors,
  MarkAllReadResponses,
  MarkPostReadData,
  MarkPostReadErrors,
  MarkPostReadResponses,
  RefreshFeedsData,
  RefreshFeedsErrors,
  RefreshFeedsResponses,
  UpdateFeedData,
  UpdateFeedErrors,
  UpdateFeedResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List all feeds
 *
 * Retrieve all RSS feeds
 */
export const listFeeds = <ThrowOnError extends boolean = false>(
  options?: Options<ListFeedsData, ThrowOnError>,
): RequestResult<ListFeedsResponses, ListFeedsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListFeedsResponses,
    ListFeedsErrors,
    ThrowOnError
  >({ url: "/feeds", ...options });

/**
 * Create a new RSS feed
 *
 * Add a new RSS feed to follow
 */
export const createFeed = <ThrowOnError extends boolean = false>(
  options: Options<CreateFeedData, ThrowOnError>,
): RequestResult<CreateFeedResponses, CreateFeedErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateFeedResponses,
    CreateFeedErrors,
    ThrowOnError
  >({
    url: "/feeds",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh feeds
 *
 * Fetch new posts from all feeds or a specific feed
 */
export const refreshFeeds = <ThrowOnError extends boolean = false>(
  options: Options<RefreshFeedsData, ThrowOnError>,
): RequestResult<RefreshFeedsResponses, RefreshFeedsErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RefreshFeedsResponses,
    RefreshFeedsErrors,
    ThrowOnError
  >({
    url: "/feeds/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a feed
 *
 * Remove an RSS feed and all its posts
 */
export const deleteFeed = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFeedData, ThrowOnError>,
): RequestResult<DeleteFeedResponses, DeleteFeedErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteFeedResponses,
    DeleteFeedErrors,
    ThrowOnError
  >({ url: "/feeds/{id}", ...options });

/**
 * Get a feed
 *
 * Retrieve a specific RSS feed by ID
 */
export const getFeed = <ThrowOnError extends boolean = false>(
  options: Options<GetFeedData, ThrowOnError>,
): RequestResult<GetFeedResponses, GetFeedErrors, ThrowOnError> =>
  (options.client ?? client).get<GetFeedResponses, GetFeedErrors, ThrowOnError>(
    { url: "/feeds/{id}", ...options },
  );

/**
 * Update a feed
 *
 * Update an existing RSS feed
 */
export const updateFeed = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFeedData, ThrowOnError>,
): RequestResult<UpdateFeedResponses, UpdateFeedErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateFeedResponses,
    UpdateFeedErrors,
    ThrowOnError
  >({
    url: "/feeds/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Mark all posts as read
 *
 * Mark all posts in a feed as read
 */
export const markAllRead = <ThrowOnError extends boolean = false>(
  options: Options<MarkAllReadData, ThrowOnError>,
): RequestResult<MarkAllReadResponses, MarkAllReadErrors, ThrowOnError> =>
  (options.client ?? client).post<
    MarkAllReadResponses,
    MarkAllReadErrors,
    ThrowOnError
  >({ url: "/feeds/{id}/mark-all-read", ...options });

/**
 * Count unread posts by feed
 *
 * Get the number of unread posts for a specific feed
 */
export const countUnreadByFeed = <ThrowOnError extends boolean = false>(
  options: Options<CountUnreadByFeedData, ThrowOnError>,
): RequestResult<
  CountUnreadByFeedResponses,
  CountUnreadByFeedErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    CountUnreadByFeedResponses,
    CountUnreadByFeedErrors,
    ThrowOnError
  >({ url: "/feeds/{id}/unread/count", ...options });

/**
 * List posts
 *
 * Retrieve posts with optional filters (feed_id, unread_only)
 */
export const listPosts = <ThrowOnError extends boolean = false>(
  options?: Options<ListPostsData, ThrowOnError>,
): RequestResult<ListPostsResponses, ListPostsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListPostsResponses,
    ListPostsErrors,
    ThrowOnError
  >({ url: "/posts", ...options });

/**
 * Count unread posts
 *
 * Get the total number of unread posts
 */
export const countUnread = <ThrowOnError extends boolean = false>(
  options?: Options<CountUnreadData, ThrowOnError>,
): RequestResult<CountUnreadResponses, CountUnreadErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    CountUnreadResponses,
    CountUnreadErrors,
    ThrowOnError
  >({ url: "/posts/unread/count", ...options });

/**
 * Get a post
 *
 * Retrieve a specific post by ID
 */
export const getPost = <ThrowOnError extends boolean = false>(
  options: Options<GetPostData, ThrowOnError>,
): RequestResult<GetPostResponses, GetPostErrors, ThrowOnError> =>
  (options.client ?? client).get<GetPostResponses, GetPostErrors, ThrowOnError>(
    { url: "/posts/{id}", ...options },
  );

/**
 * Mark post as read/unread
 *
 * Update the read status of a post
 */
export const markPostRead = <ThrowOnError extends boolean = false>(
  options: Options<MarkPostReadData, ThrowOnError>,
): RequestResult<MarkPostReadResponses, MarkPostReadErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    MarkPostReadResponses,
    MarkPostReadErrors,
    ThrowOnError
  >({
    url: "/posts/{id}/read",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
