// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type CountUnreadOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  count: number;
};

export type ErrorDetail = {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: unknown;
};

export type ErrorModel = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type FeedResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  created_at: string;
  description?: string;
  id: number;
  last_fetched_at?: string;
  link?: string;
  title: string;
  updated_at: string;
  url: string;
};

export type Input = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  description?: string;
  link?: string;
  title: string;
  url: string;
};

export type MarkReadRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  is_read: boolean;
};

export type PostResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  author?: string;
  content?: string;
  created_at: string;
  description?: string;
  feed_id: number;
  guid: string;
  id: number;
  is_read: boolean;
  link: string;
  published_at?: string;
  title: string;
  updated_at: string;
};

export type RefreshRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Optional feed ID to refresh specific feed
   */
  feed_id?: number;
};

export type RefreshResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  feeds_updated: number;
  message: string;
  posts_added: number;
};

export type CountUnreadOutputBodyWritable = {
  count: number;
};

export type ErrorModelWritable = {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type FeedResponseWritable = {
  created_at: string;
  description?: string;
  id: number;
  last_fetched_at?: string;
  link?: string;
  title: string;
  updated_at: string;
  url: string;
};

export type InputWritable = {
  description?: string;
  link?: string;
  title: string;
  url: string;
};

export type MarkReadRequestWritable = {
  is_read: boolean;
};

export type PostResponseWritable = {
  author?: string;
  content?: string;
  created_at: string;
  description?: string;
  feed_id: number;
  guid: string;
  id: number;
  is_read: boolean;
  link: string;
  published_at?: string;
  title: string;
  updated_at: string;
};

export type RefreshRequestWritable = {
  /**
   * Optional feed ID to refresh specific feed
   */
  feed_id?: number;
};

export type RefreshResponseWritable = {
  feeds_updated: number;
  message: string;
  posts_added: number;
};

export type ListFeedsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/feeds";
};

export type ListFeedsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListFeedsError = ListFeedsErrors[keyof ListFeedsErrors];

export type ListFeedsResponses = {
  /**
   * OK
   */
  200: Array<FeedResponse> | null;
};

export type ListFeedsResponse = ListFeedsResponses[keyof ListFeedsResponses];

export type CreateFeedData = {
  body: InputWritable;
  path?: never;
  query?: never;
  url: "/feeds";
};

export type CreateFeedErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateFeedError = CreateFeedErrors[keyof CreateFeedErrors];

export type CreateFeedResponses = {
  /**
   * Created
   */
  201: FeedResponse;
};

export type CreateFeedResponse = CreateFeedResponses[keyof CreateFeedResponses];

export type RefreshFeedsData = {
  body: RefreshRequestWritable;
  path?: never;
  query?: never;
  url: "/feeds/refresh";
};

export type RefreshFeedsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type RefreshFeedsError = RefreshFeedsErrors[keyof RefreshFeedsErrors];

export type RefreshFeedsResponses = {
  /**
   * OK
   */
  200: RefreshResponse;
};

export type RefreshFeedsResponse =
  RefreshFeedsResponses[keyof RefreshFeedsResponses];

export type DeleteFeedData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/feeds/{id}";
};

export type DeleteFeedErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type DeleteFeedError = DeleteFeedErrors[keyof DeleteFeedErrors];

export type DeleteFeedResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteFeedResponse = DeleteFeedResponses[keyof DeleteFeedResponses];

export type GetFeedData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/feeds/{id}";
};

export type GetFeedErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetFeedError = GetFeedErrors[keyof GetFeedErrors];

export type GetFeedResponses = {
  /**
   * OK
   */
  200: FeedResponse;
};

export type GetFeedResponse = GetFeedResponses[keyof GetFeedResponses];

export type UpdateFeedData = {
  body: InputWritable;
  path: {
    id: number;
  };
  query?: never;
  url: "/feeds/{id}";
};

export type UpdateFeedErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type UpdateFeedError = UpdateFeedErrors[keyof UpdateFeedErrors];

export type UpdateFeedResponses = {
  /**
   * OK
   */
  200: FeedResponse;
};

export type UpdateFeedResponse = UpdateFeedResponses[keyof UpdateFeedResponses];

export type MarkAllReadData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/feeds/{id}/mark-all-read";
};

export type MarkAllReadErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type MarkAllReadError = MarkAllReadErrors[keyof MarkAllReadErrors];

export type MarkAllReadResponses = {
  /**
   * No Content
   */
  204: void;
};

export type MarkAllReadResponse =
  MarkAllReadResponses[keyof MarkAllReadResponses];

export type CountUnreadByFeedData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/feeds/{id}/unread/count";
};

export type CountUnreadByFeedErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CountUnreadByFeedError =
  CountUnreadByFeedErrors[keyof CountUnreadByFeedErrors];

export type CountUnreadByFeedResponses = {
  /**
   * OK
   */
  200: CountUnreadOutputBody;
};

export type CountUnreadByFeedResponse =
  CountUnreadByFeedResponses[keyof CountUnreadByFeedResponses];

export type ListPostsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
    /**
     * Filter by feed ID (0 = all feeds)
     */
    feed_id?: number;
    /**
     * Show only unread posts
     */
    unread_only?: boolean;
  };
  url: "/posts";
};

export type ListPostsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListPostsError = ListPostsErrors[keyof ListPostsErrors];

export type ListPostsResponses = {
  /**
   * OK
   */
  200: Array<PostResponse> | null;
};

export type ListPostsResponse = ListPostsResponses[keyof ListPostsResponses];

export type CountUnreadData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/posts/unread/count";
};

export type CountUnreadErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CountUnreadError = CountUnreadErrors[keyof CountUnreadErrors];

export type CountUnreadResponses = {
  /**
   * OK
   */
  200: CountUnreadOutputBody;
};

export type CountUnreadResponse =
  CountUnreadResponses[keyof CountUnreadResponses];

export type GetPostData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/posts/{id}";
};

export type GetPostErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
  /**
   * OK
   */
  200: PostResponse;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type MarkPostReadData = {
  body: MarkReadRequestWritable;
  path: {
    id: number;
  };
  query?: never;
  url: "/posts/{id}/read";
};

export type MarkPostReadErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type MarkPostReadError = MarkPostReadErrors[keyof MarkPostReadErrors];

export type MarkPostReadResponses = {
  /**
   * No Content
   */
  204: void;
};

export type MarkPostReadResponse =
  MarkPostReadResponses[keyof MarkPostReadResponses];
