// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  countUnread,
  countUnreadByFeed,
  createFeed,
  deleteFeed,
  getFeed,
  getPost,
  listFeeds,
  listPosts,
  markAllRead,
  markPostRead,
  type Options,
  refreshFeeds,
  updateFeed,
} from "../sdk.gen";
import type {
  CountUnreadByFeedData,
  CountUnreadByFeedError,
  CountUnreadByFeedResponse,
  CountUnreadData,
  CountUnreadError,
  CountUnreadResponse,
  CreateFeedData,
  CreateFeedError,
  CreateFeedResponse,
  DeleteFeedData,
  DeleteFeedError,
  DeleteFeedResponse,
  GetFeedData,
  GetFeedError,
  GetFeedResponse,
  GetPostData,
  GetPostError,
  GetPostResponse,
  ListFeedsData,
  ListFeedsError,
  ListFeedsResponse,
  ListPostsData,
  ListPostsError,
  ListPostsResponse,
  MarkAllReadData,
  MarkAllReadError,
  MarkAllReadResponse,
  MarkPostReadData,
  MarkPostReadError,
  MarkPostReadResponse,
  RefreshFeedsData,
  RefreshFeedsError,
  RefreshFeedsResponse,
  UpdateFeedData,
  UpdateFeedError,
  UpdateFeedResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listFeedsQueryKey = (options?: Options<ListFeedsData>) =>
  createQueryKey("listFeeds", options);

/**
 * List all feeds
 *
 * Retrieve all RSS feeds
 */
export const listFeedsOptions = (options?: Options<ListFeedsData>) =>
  queryOptions<
    ListFeedsResponse,
    ListFeedsError,
    ListFeedsResponse,
    ReturnType<typeof listFeedsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFeeds({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFeedsQueryKey(options),
  });

/**
 * Create a new RSS feed
 *
 * Add a new RSS feed to follow
 */
export const createFeedMutation = (
  options?: Partial<Options<CreateFeedData>>,
): UseMutationOptions<
  CreateFeedResponse,
  CreateFeedError,
  Options<CreateFeedData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateFeedResponse,
    CreateFeedError,
    Options<CreateFeedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createFeed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh feeds
 *
 * Fetch new posts from all feeds or a specific feed
 */
export const refreshFeedsMutation = (
  options?: Partial<Options<RefreshFeedsData>>,
): UseMutationOptions<
  RefreshFeedsResponse,
  RefreshFeedsError,
  Options<RefreshFeedsData>
> => {
  const mutationOptions: UseMutationOptions<
    RefreshFeedsResponse,
    RefreshFeedsError,
    Options<RefreshFeedsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshFeeds({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a feed
 *
 * Remove an RSS feed and all its posts
 */
export const deleteFeedMutation = (
  options?: Partial<Options<DeleteFeedData>>,
): UseMutationOptions<
  DeleteFeedResponse,
  DeleteFeedError,
  Options<DeleteFeedData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteFeedResponse,
    DeleteFeedError,
    Options<DeleteFeedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteFeed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFeedQueryKey = (options: Options<GetFeedData>) =>
  createQueryKey("getFeed", options);

/**
 * Get a feed
 *
 * Retrieve a specific RSS feed by ID
 */
export const getFeedOptions = (options: Options<GetFeedData>) =>
  queryOptions<
    GetFeedResponse,
    GetFeedError,
    GetFeedResponse,
    ReturnType<typeof getFeedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFeed({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFeedQueryKey(options),
  });

/**
 * Update a feed
 *
 * Update an existing RSS feed
 */
export const updateFeedMutation = (
  options?: Partial<Options<UpdateFeedData>>,
): UseMutationOptions<
  UpdateFeedResponse,
  UpdateFeedError,
  Options<UpdateFeedData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateFeedResponse,
    UpdateFeedError,
    Options<UpdateFeedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateFeed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Mark all posts as read
 *
 * Mark all posts in a feed as read
 */
export const markAllReadMutation = (
  options?: Partial<Options<MarkAllReadData>>,
): UseMutationOptions<
  MarkAllReadResponse,
  MarkAllReadError,
  Options<MarkAllReadData>
> => {
  const mutationOptions: UseMutationOptions<
    MarkAllReadResponse,
    MarkAllReadError,
    Options<MarkAllReadData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await markAllRead({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const countUnreadByFeedQueryKey = (
  options: Options<CountUnreadByFeedData>,
) => createQueryKey("countUnreadByFeed", options);

/**
 * Count unread posts by feed
 *
 * Get the number of unread posts for a specific feed
 */
export const countUnreadByFeedOptions = (
  options: Options<CountUnreadByFeedData>,
) =>
  queryOptions<
    CountUnreadByFeedResponse,
    CountUnreadByFeedError,
    CountUnreadByFeedResponse,
    ReturnType<typeof countUnreadByFeedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await countUnreadByFeed({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: countUnreadByFeedQueryKey(options),
  });

export const listPostsQueryKey = (options?: Options<ListPostsData>) =>
  createQueryKey("listPosts", options);

/**
 * List posts
 *
 * Retrieve posts with optional filters (feed_id, unread_only)
 */
export const listPostsOptions = (options?: Options<ListPostsData>) =>
  queryOptions<
    ListPostsResponse,
    ListPostsError,
    ListPostsResponse,
    ReturnType<typeof listPostsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPosts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listPostsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listPostsInfiniteQueryKey = (
  options?: Options<ListPostsData>,
): QueryKey<Options<ListPostsData>> =>
  createQueryKey("listPosts", options, true);

/**
 * List posts
 *
 * Retrieve posts with optional filters (feed_id, unread_only)
 */
export const listPostsInfiniteOptions = (options?: Options<ListPostsData>) => {
  const opts = infiniteQueryOptions<
    ListPostsResponse,
    ListPostsError,
    InfiniteData<ListPostsResponse>,
    QueryKey<Options<ListPostsData>>,
    | number
    | Pick<
        QueryKey<Options<ListPostsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListPostsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listPosts({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listPostsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const countUnreadQueryKey = (options?: Options<CountUnreadData>) =>
  createQueryKey("countUnread", options);

/**
 * Count unread posts
 *
 * Get the total number of unread posts
 */
export const countUnreadOptions = (options?: Options<CountUnreadData>) =>
  queryOptions<
    CountUnreadResponse,
    CountUnreadError,
    CountUnreadResponse,
    ReturnType<typeof countUnreadQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await countUnread({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: countUnreadQueryKey(options),
  });

export const getPostQueryKey = (options: Options<GetPostData>) =>
  createQueryKey("getPost", options);

/**
 * Get a post
 *
 * Retrieve a specific post by ID
 */
export const getPostOptions = (options: Options<GetPostData>) =>
  queryOptions<
    GetPostResponse,
    GetPostError,
    GetPostResponse,
    ReturnType<typeof getPostQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPostQueryKey(options),
  });

/**
 * Mark post as read/unread
 *
 * Update the read status of a post
 */
export const markPostReadMutation = (
  options?: Partial<Options<MarkPostReadData>>,
): UseMutationOptions<
  MarkPostReadResponse,
  MarkPostReadError,
  Options<MarkPostReadData>
> => {
  const mutationOptions: UseMutationOptions<
    MarkPostReadResponse,
    MarkPostReadError,
    Options<MarkPostReadData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await markPostRead({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
