/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export interface AddFeedInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @maxLength 80 */
  name?: string;
  url: string;
}
