/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Roe API
 * OpenAPI spec version: 1.0.0
 */

export interface AddFeedInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @maxLength 80 */
  name?: string;
  url: string;
}
