/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Roe API
 * OpenAPI spec version: 1.0.0
 */
import type { Feed } from './feed';

export interface AddFeedOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  feed: Feed;
}
