/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Roe API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetail } from './errorDetail';

/**
 * Optional list of individual error details
 */
export type ErrorModelErrors = ErrorDetail[] | null;
