/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export interface FeedContent {
  content: string;
  description: string;
  feed_id: number;
  id: number;
  is_read: boolean;
  link: string;
  title: string;
}
