/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export interface GetFeedItemsRow {
  content: string;
  description: string;
  id: number;
  is_read: boolean;
  link: string;
  title: string;
}
