/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Roe API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeedsOutputBodyFeeds } from './getFeedsOutputBodyFeeds';

export interface GetFeedsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  feeds: GetFeedsOutputBodyFeeds;
}
