/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Roe API
 * OpenAPI spec version: 1.0.0
 */

export interface GetFeedsRow {
  id: number;
  name: string;
  unreadItemsCount: number;
  url: string;
}
