/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Roe API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeedItemsRow } from './getFeedItemsRow';

export type GetFeedItemsOutputBodyItems = GetFeedItemsRow[] | null;
