/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeedsOutputBodyFeeds } from './getFeedsOutputBodyFeeds';

export interface GetFeedsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  feeds: GetFeedsOutputBodyFeeds;
}
