/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeedsRow } from './getFeedsRow';

export type GetFeedsOutputBodyFeeds = GetFeedsRow[] | null;
