/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export interface GetFeedsRow {
  id: number;
  name: string;
  unread_items_count: number;
  url: string;
}
