/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export interface GetFeedItemRow {
  content: string;
  description: string;
  id: number;
  is_read: number;
  link: string;
  title: string;
}
