/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Roe API
 * OpenAPI spec version: 1.0.0
 */

export interface GetFeedItemsRow {
  content: string;
  description: string;
  id: number;
  isRead: boolean;
  link: string;
  title: string;
}
