/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeedItemsRow } from './getFeedItemsRow';

export type GetFeedItemsOutputBodyItems = GetFeedItemsRow[] | null;
