/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFeedItemsOutputBodyItems } from './getFeedItemsOutputBodyItems';

export interface GetFeedItemsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  items: GetFeedItemsOutputBodyItems;
}
