/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export * from './addFeedInputBody';
export * from './addFeedOutputBody';
export * from './errorDetail';
export * from './errorModel';
export * from './errorModelErrors';
export * from './feed';
export * from './feedContent';
export * from './getFeedItemOutputBody';
export * from './getFeedItemRow';
export * from './getFeedItemsOutputBody';
export * from './getFeedItemsOutputBodyItems';
export * from './getFeedItemsRow';
export * from './getFeedsOutputBody';
export * from './getFeedsOutputBodyFeeds';
export * from './getFeedsRow';
export * from './updateFeedItemInputBody';
export * from './updateFeedItemOutputBody';