/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Roe API
 * OpenAPI spec version: 1.0.0
 */
import type { FeedContent } from './feedContent';

export interface UpdateFeedItemOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  item: FeedContent;
}
