// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (title, url, description, link)
VALUES ($1, $2, $3, $4)
RETURNING id, title, url, description, link, last_fetched_at, created_at, updated_at
`

type CreateFeedParams struct {
	Title       string      `json:"title"`
	Url         string      `json:"url"`
	Description pgtype.Text `json:"description"`
	Link        pgtype.Text `json:"link"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, createFeed,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.Link,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Link,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds
WHERE id = $1
`

func (q *Queries) DeleteFeed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFeed, id)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT id, title, url, description, link, last_fetched_at, created_at, updated_at FROM feeds
WHERE id = $1
`

func (q *Queries) GetFeed(ctx context.Context, id int32) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Link,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, title, url, description, link, last_fetched_at, created_at, updated_at FROM feeds
WHERE url = $1
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Link,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, title, url, description, link, last_fetched_at, created_at, updated_at FROM feeds
ORDER BY created_at DESC
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.Link,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET title = $2, description = $3, link = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, title, url, description, link, last_fetched_at, created_at, updated_at
`

type UpdateFeedParams struct {
	ID          int32       `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Link        pgtype.Text `json:"link"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, updateFeed,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Link,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Link,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFeedLastFetched = `-- name: UpdateFeedLastFetched :exec
UPDATE feeds
SET last_fetched_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateFeedLastFetched(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateFeedLastFetched, id)
	return err
}
