// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID            int32            `json:"id"`
	Title         string           `json:"title"`
	Url           string           `json:"url"`
	Description   pgtype.Text      `json:"description"`
	Link          pgtype.Text      `json:"link"`
	LastFetchedAt pgtype.Timestamp `json:"last_fetched_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Post struct {
	ID          int32            `json:"id"`
	FeedID      int32            `json:"feed_id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Content     pgtype.Text      `json:"content"`
	Link        string           `json:"link"`
	Author      pgtype.Text      `json:"author"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Guid        string           `json:"guid"`
	IsRead      bool             `json:"is_read"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
