// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadPosts = `-- name: CountUnreadPosts :one
SELECT COUNT(*) FROM posts
WHERE is_read = FALSE
`

func (q *Queries) CountUnreadPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadPostsByFeed = `-- name: CountUnreadPostsByFeed :one
SELECT COUNT(*) FROM posts
WHERE feed_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadPostsByFeed(ctx context.Context, feedID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadPostsByFeed, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (feed_id, title, description, content, link, author, published_at, guid)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (feed_id, guid) DO UPDATE
SET title = EXCLUDED.title,
    description = EXCLUDED.description,
    content = EXCLUDED.content,
    link = EXCLUDED.link,
    author = EXCLUDED.author,
    published_at = EXCLUDED.published_at,
    updated_at = NOW()
RETURNING id, feed_id, title, description, content, link, author, published_at, guid, is_read, created_at, updated_at
`

type CreatePostParams struct {
	FeedID      int32            `json:"feed_id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Content     pgtype.Text      `json:"content"`
	Link        string           `json:"link"`
	Author      pgtype.Text      `json:"author"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Guid        string           `json:"guid"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.FeedID,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Link,
		arg.Author,
		arg.PublishedAt,
		arg.Guid,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Link,
		&i.Author,
		&i.PublishedAt,
		&i.Guid,
		&i.IsRead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, feed_id, title, description, content, link, author, published_at, guid, is_read, created_at, updated_at FROM posts
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Link,
		&i.Author,
		&i.PublishedAt,
		&i.Guid,
		&i.IsRead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, feed_id, title, description, content, link, author, published_at, guid, is_read, created_at, updated_at FROM posts
ORDER BY published_at DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Link,
			&i.Author,
			&i.PublishedAt,
			&i.Guid,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByFeed = `-- name: ListPostsByFeed :many
SELECT id, feed_id, title, description, content, link, author, published_at, guid, is_read, created_at, updated_at FROM posts
WHERE feed_id = $1
ORDER BY published_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListPostsByFeedParams struct {
	FeedID int32 `json:"feed_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPostsByFeed(ctx context.Context, arg ListPostsByFeedParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByFeed, arg.FeedID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Link,
			&i.Author,
			&i.PublishedAt,
			&i.Guid,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadPosts = `-- name: ListUnreadPosts :many
SELECT id, feed_id, title, description, content, link, author, published_at, guid, is_read, created_at, updated_at FROM posts
WHERE is_read = FALSE
ORDER BY published_at DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListUnreadPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUnreadPosts(ctx context.Context, arg ListUnreadPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listUnreadPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Link,
			&i.Author,
			&i.PublishedAt,
			&i.Guid,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadPostsByFeed = `-- name: ListUnreadPostsByFeed :many
SELECT id, feed_id, title, description, content, link, author, published_at, guid, is_read, created_at, updated_at FROM posts
WHERE feed_id = $1 AND is_read = FALSE
ORDER BY published_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListUnreadPostsByFeedParams struct {
	FeedID int32 `json:"feed_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUnreadPostsByFeed(ctx context.Context, arg ListUnreadPostsByFeedParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listUnreadPostsByFeed, arg.FeedID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Link,
			&i.Author,
			&i.PublishedAt,
			&i.Guid,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllPostsAsRead = `-- name: MarkAllPostsAsRead :exec
UPDATE posts
SET is_read = TRUE, updated_at = NOW()
WHERE feed_id = $1
`

func (q *Queries) MarkAllPostsAsRead(ctx context.Context, feedID int32) error {
	_, err := q.db.Exec(ctx, markAllPostsAsRead, feedID)
	return err
}

const markPostAsRead = `-- name: MarkPostAsRead :exec
UPDATE posts
SET is_read = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPostAsRead(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markPostAsRead, id)
	return err
}

const markPostAsUnread = `-- name: MarkPostAsUnread :exec
UPDATE posts
SET is_read = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPostAsUnread(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markPostAsUnread, id)
	return err
}
