// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountUnreadPosts(ctx context.Context) (int64, error)
	CountUnreadPostsByFeed(ctx context.Context, feedID int32) (int64, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DeleteFeed(ctx context.Context, id int32) error
	DeletePost(ctx context.Context, id int32) error
	GetFeed(ctx context.Context, id int32) (Feed, error)
	GetFeedByURL(ctx context.Context, url string) (Feed, error)
	GetPost(ctx context.Context, id int32) (Post, error)
	ListFeeds(ctx context.Context) ([]Feed, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListPostsByFeed(ctx context.Context, arg ListPostsByFeedParams) ([]Post, error)
	ListUnreadPosts(ctx context.Context, arg ListUnreadPostsParams) ([]Post, error)
	ListUnreadPostsByFeed(ctx context.Context, arg ListUnreadPostsByFeedParams) ([]Post, error)
	MarkAllPostsAsRead(ctx context.Context, feedID int32) error
	MarkPostAsRead(ctx context.Context, id int32) error
	MarkPostAsUnread(ctx context.Context, id int32) error
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
	UpdateFeedLastFetched(ctx context.Context, id int32) error
}

var _ Querier = (*Queries)(nil)
